Repository acroquelois/flutter-flip-card, pull requests merged in 2020-10, with the labels that each got.

#12 :building_construction: refacto routing
  lib/const/colors.dart
  lib/main.dart
  lib/router/router.dart
  lib/ui/components/bottom_bar/fab_bottom_bar.dart
  lib/ui/layouts/layout.dart
  lib/ui/pages/setting.dart
  lib/ui/themes/theme.dart
Labels: archi

#14 🐛 fix router name
  lib/router/router_app.dart
  lib/ui/layouts/layout.dart
Labels: bug

#13 :sparkles: Insert word
  assets/google-translate.svg
  lib/const/theme.dart
  lib/data/data_sources/remote_data_source/dio_helper.dart
  lib/data/data_sources/remote_data_source/translate_helper.dart
  lib/main.dart
  lib/router/router_app.dart
  lib/service/language_service.dart
  lib/ui/components/add_word.dart
  lib/ui/components/button/icon_text_button.dart
  lib/ui/components/button/square_button.dart
  lib/ui/components/input/word_input.dart
  lib/ui/layouts/layout.dart
  lib/ui/pages/add_word.dart
  pubspec.lock
  pubspec.yaml
Labels: dev

#19 ✨ Firebase base setup
  android/app/src/google-services.json
  lib/data/firebase_auth_provider.dart
  lib/main.dart
  lib/service/firebaseServices/firebase_auth_service.dart
  lib/ui/pages/profile.dart
  pubspec.lock
  pubspec.yaml
Labels: api

#25 :apple: it works on iOS
  ios/.gitignore
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/README.md
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
Labels: OS
